version: '3.2'

services:
  app:
    container_name: safraapishare
    image: safraapishare
    enviroment:
      - PORT=5000
    ports:
      - 5000:5000
    build:
      context: ""
      dockerfile: Dockerfile
  sqlite:
    image: mssqllocaldb
    volumes:
      -localdb: /var/lib/sqlite
      enviroment:
        SQL_DATABASE: DBSafra        